apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: ey-node-app
    appstudio.openshift.io/component: devfile-sample-vata
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-vata
  namespace: eyuen-tenant
spec:
  url: https://github.com/elsony/devfile-sample
